In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Data Collection and Pre-Processing


In [ ]:
#loading the data from the csv file to a panda dataframe

movies_data = pd.read_csv('/content/movies.csv')



In [ ]:
#printing first 5 rows of dataframe
movies_data.head()


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
#number of rows and cols

movies_data.shape

(4803, 24)

In [ ]:
#selecting relevent features for recommendation

selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
movies_data

index     budget                                             genres  \
0         0  237000000  <bound method Series.fillna of 0       Action ...   
1         1  300000000  <bound method Series.fillna of 0       Action ...   
2         2  245000000  <bound method Series.fillna of 0       Action ...   
3         3  250000000  <bound method Series.fillna of 0       Action ...   
4         4  260000000  <bound method Series.fillna of 0       Action ...   
...     ...        ...                                                ...   
4798   4798     220000  <bound method Series.fillna of 0       Action ...   
4799   4799       9000  <bound method Series.fillna of 0       Action ...   
4800   4800          0  <bound method Series.fillna of 0       Action ...   
4801   4801          0  <bound method Series.fillna of 0       Action ...   
4802   4802          0  <bound method Series.fillna of 0       Action ...   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     <bound method Series.fillna of 0       culture...                en   
1     <bound method Series.fillna of 0       culture...                en   
2     <bound method Series.fillna of 0       culture...                en   
3     <bound method Series.fillna of 0       culture...                en   
4     <bound method Series.fillna of 0       culture...                en   
...                                                 ...               ...   
4798  <bound method Series.fillna of 0       culture...                es   
4799  <bound method Series.fillna of 0       culture...                en   
4800  <bound method Series.fillna of 0       culture...                en   
4801  <bound method Series.fillna of 0       culture...                en   
4802  <bound method Series.fillna of 0       culture...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...   
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.44447

In [ ]:
# Combine features into a single column
movies_data['combined_features'] = movies_data['genres'] + ' ' + movies_data['keywords'] + ' ' + movies_data['tagline'] + ' ' + movies_data['cast'] + ' ' + movies_data['director']

# Display the first few rows to inspect the combined features
print(movies_data['combined_features'].head())


0    <bound method Series.fillna of 0       Action ...
1    <bound method Series.fillna of 0       Action ...
2    <bound method Series.fillna of 0       Action ...
3    <bound method Series.fillna of 0       Action ...
4    <bound method Series.fillna of 0       Action ...
Name: combined_features, dtype: object


In [ ]:
print(combined_features)

0       <bound method Series.fillna of 0       Action ...
1       <bound method Series.fillna of 0       Action ...
2       <bound method Series.fillna of 0       Action ...
3       <bound method Series.fillna of 0       Action ...
4       <bound method Series.fillna of 0       Action ...
                              ...                        
4798    <bound method Series.fillna of 0       Action ...
4799    <bound method Series.fillna of 0       Action ...
4800    <bound method Series.fillna of 0       Action ...
4801    <bound method Series.fillna of 0       Action ...
4802    <bound method Series.fillna of 0       Action ...
Length: 4803, dtype: object


In [ ]:
#converting the text data to feature vector

vectorizer = TfidfVectorizer()


In [ ]:
# Fit and transform the combined features into feature vectors
feature_vectors = vectorizer.fit_transform(movies_data['combined_features'])


In [ ]:
# Display the shape of the feature vectors to ensure they are correctly generated
print(feature_vectors.shape)

(4803, 201)


In [ ]:
print(feature_vectors)

  (0, 59)	0.035578403348241
  (0, 95)	0.035578403348241
  (0, 169)	0.035578403348241
  (0, 161)	0.035578403348241
  (0, 154)	0.035578403348241
  (0, 153)	0.035578403348241
  (0, 173)	0.035578403348241
  (0, 11)	0.035578403348241
  (0, 136)	0.035578403348241
  (0, 37)	0.035578403348241
  (0, 124)	0.035578403348241
  (0, 192)	0.035578403348241
  (0, 89)	0.035578403348241
  (0, 32)	0.035578403348241
  (0, 103)	0.035578403348241
  (0, 34)	0.035578403348241
  (0, 76)	0.035578403348241
  (0, 44)	0.035578403348241
  (0, 92)	0.071156806696482
  (0, 26)	0.071156806696482
  (0, 18)	0.035578403348241
  (0, 63)	0.035578403348241
  (0, 156)	0.035578403348241
  (0, 10)	0.035578403348241
  (0, 149)	0.035578403348241
  :	:
  (4802, 130)	0.177892016741205
  (4802, 60)	0.035578403348241
  (4802, 4)	0.177892016741205
  (4802, 131)	0.177892016741205
  (4802, 3)	0.177892016741205
  (4802, 129)	0.035578403348241
  (4802, 186)	0.035578403348241
  (4802, 2)	0.177892016741205
  (4802, 155)	0.071156806696482
  

Cosine Similarity


In [ ]:
# Compute cosine similarity matrix

similarity = cosine_similarity(feature_vectors)

In [ ]:
# Display the similarity matrix to inspect the values

print(similarity)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [ ]:
print(similarity.shape)


(4803, 4803)


Getting Movie Name from user


In [ ]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : iron man


In [ ]:
#creating a list with all movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [ ]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

68


In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.9999999999999998), (1, 0.9999999999999998), (2, 0.9999999999999998), (3, 0.9999999999999998), (4, 0.9999999999999998), (5, 0.9999999999999998), (6, 0.9999999999999998), (7, 0.9999999999999998), (8, 0.9999999999999998), (9, 0.9999999999999998), (10, 0.9999999999999998), (11, 0.9999999999999998), (12, 0.9999999999999998), (13, 0.9999999999999998), (14, 0.9999999999999998), (15, 0.9999999999999998), (16, 0.9999999999999998), (17, 0.9999999999999998), (18, 0.9999999999999998), (19, 0.9999999999999998), (20, 0.9999999999999998), (21, 0.9999999999999998), (22, 0.9999999999999998), (23, 0.9999999999999998), (24, 0.9999999999999998), (25, 0.9999999999999998), (26, 0.9999999999999998), (27, 0.9999999999999998), (28, 0.9999999999999998), (29, 0.9999999999999998), (30, 0.9999999999999998), (31, 0.9999999999999998), (32, 0.9999999999999998), (33, 0.9999999999999998), (34, 0.9999999999999998), (35, 0.9999999999999998), (36, 0.9999999999999998), (37, 0.9999999999999998), (38, 0.99999999999999

In [ ]:
len(similarity_score)

4803

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(0, 0.9999999999999998), (1, 0.9999999999999998), (2, 0.9999999999999998), (3, 0.9999999999999998), (4, 0.9999999999999998), (5, 0.9999999999999998), (6, 0.9999999999999998), (7, 0.9999999999999998), (8, 0.9999999999999998), (9, 0.9999999999999998), (10, 0.9999999999999998), (11, 0.9999999999999998), (12, 0.9999999999999998), (13, 0.9999999999999998), (14, 0.9999999999999998), (15, 0.9999999999999998), (16, 0.9999999999999998), (17, 0.9999999999999998), (18, 0.9999999999999998), (19, 0.9999999999999998), (20, 0.9999999999999998), (21, 0.9999999999999998), (22, 0.9999999999999998), (23, 0.9999999999999998), (24, 0.9999999999999998), (25, 0.9999999999999998), (26, 0.9999999999999998), (27, 0.9999999999999998), (28, 0.9999999999999998), (29, 0.9999999999999998), (30, 0.9999999999999998), (31, 0.9999999999999998), (32, 0.9999999999999998), (33, 0.9999999999999998), (34, 0.9999999999999998), (35, 0.9999999999999998), (36, 0.9999999999999998), (37, 0.9999999999999998), (38, 0.99999999999999

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Avatar
2 . Pirates of the Caribbean: At World's End
3 . Spectre
4 . The Dark Knight Rises
5 . John Carter
6 . Spider-Man 3
7 . Tangled
8 . Avengers: Age of Ultron
9 . Harry Potter and the Half-Blood Prince
10 . Batman v Superman: Dawn of Justice
11 . Superman Returns
12 . Quantum of Solace
13 . Pirates of the Caribbean: Dead Man's Chest
14 . The Lone Ranger
15 . Man of Steel
16 . The Chronicles of Narnia: Prince Caspian
17 . The Avengers
18 . Pirates of the Caribbean: On Stranger Tides
19 . Men in Black 3
20 . The Hobbit: The Battle of the Five Armies
21 . The Amazing Spider-Man
22 . Robin Hood
23 . The Hobbit: The Desolation of Smaug
24 . The Golden Compass
25 . King Kong
26 . Titanic
27 . Captain America: Civil War
28 . Battleship
29 . Jurassic World


Movie Recommendation System


In [ ]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : BatMan
Movies suggested for you : 

1 . Avatar
2 . Pirates of the Caribbean: At World's End
3 . Spectre
4 . The Dark Knight Rises
5 . John Carter
6 . Spider-Man 3
7 . Tangled
8 . Avengers: Age of Ultron
9 . Harry Potter and the Half-Blood Prince
10 . Batman v Superman: Dawn of Justice
11 . Superman Returns
12 . Quantum of Solace
13 . Pirates of the Caribbean: Dead Man's Chest
14 . The Lone Ranger
15 . Man of Steel
16 . The Chronicles of Narnia: Prince Caspian
17 . The Avengers
18 . Pirates of the Caribbean: On Stranger Tides
19 . Men in Black 3
20 . The Hobbit: The Battle of the Five Armies
21 . The Amazing Spider-Man
22 . Robin Hood
23 . The Hobbit: The Desolation of Smaug
24 . The Golden Compass
25 . King Kong
26 . Titanic
27 . Captain America: Civil War
28 . Battleship
29 . Jurassic World
